### PR TITLE
Changing to using BHoM join instead of RhinoJoin when converting polycurves to avoid Rhino Crash

### LINKED ISSUE #220: Calling Rhino.Join from convert to Polycurve sometimes leads to a full Rhino crash
#### Description:

In some cases, especially if dragging sliders and rapidly changing geometry Rhino crashes. A case identified looking at the Rhino crash report is the call to Rhino Join curves here:

https://github.com/BHoM/Rhinoceros_Toolkit/blob/ebe6f06321d0c3a90946d142664297e49d66a2de/Rhinoceros_Engine/Convert/ToRhino.cs#L278

The error thrown is a System access violation exception from the unmanaged c++ backend of rhino, and is not an exception that can be caught and is as mentioned leading to a full on Rhino crash.

#### Steps to reproduce:

Slightly tricky to reproduce as only happening sporadically. Cases found so far is when trying to display a significant amount of Poly curves at the same time and then rapidly changing them by, for example, dragging a slider in GH.

#### Expected behaviour:

For the same functional behaviour to remain, but avoiding making the risky call to the rhino method. Suggestion is to check if the curves are joined using BHoM methods instead of relying on the rhino ones.

#### Test file(s):

Will be provided in the PR.

Issue linked to #113 that introduced those lines

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #220

Using BHoM Join instead of Rhino join to check if the curve can be coverted.

This is to avoid full blown crashes of Rhino from happening that can for some cases be triggered by the Rhino.Join method that was used.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Rhinoceros_Toolkit/%23221-AvoidCallingRhinoJoinToStopRhinoCrashWhenConvertingPolycurves?csf=1&web=1&e=UMB25Z

### CODE REVIEW

File: Rhinoceros_Engine/Convert/ToRhino.cs [hunk 1]
```diff
@@ -272,10 +272,16 @@ public static RHG.PolyCurve ToRhino(this BHG.PolyCurve bPolyCurve)
...
+            //Rhino Join is throwing access violation exceptions in some cases, leading to a full rhino crash, that can not be caught by a try-catch.
+            //For this reason, the BHoM Join is used instead.
+            if (BH.Engine.Geometry.Compute.IJoin(bPolyCurve.Curves).Count > 1)
+                return null;    //Not returning error message here as that will lead to confusing messages on any method returning a disjointed Polycurve deemed valid in BHoM.
+
             IEnumerable<RHG.Curve> parts = bPolyCurve.Curves.Select(x => x.IToRhino());
 
-            // Check if bPolycurve is made of disconnected segments
-            if (RHG.Curve.JoinCurves(parts).Length > 1)
+            if (parts.Any(x => x == null))
```
Comment (FraserGreenroyd) [inline Rhinoceros_Engine/Convert/ToRhino.cs:284]: Is it worth stripping out the `null` elements and then checking if the remaining count is greater than 1? That way, if for some reason `parts` gets 2 elements, 1 valid and 1 null, we could return the valid curve after removing the `null`? Whereas if we get 3 elements, 2 valid and 1 null, we can still return null here as it was previously?

File: Rhinoceros_Engine/Convert/ToRhino.cs [hunk 2]
```diff
@@ -272,10 +272,16 @@ public static RHG.PolyCurve ToRhino(this BHG.PolyCurve bPolyCurve)
             if (bPolyCurve == null)
                 return null;
 
+            //Curve is checked that it is a joined curve and only converted if that is the case.
```
Comment (FraserGreenroyd) [inline Rhinoceros_Engine/Convert/ToRhino.cs:275]: Can we add the date for which this comment becomes valid - beneficial in case we ever want to look back if a future issue arises and work out how we got to this solution.

File: Rhinoceros_Engine/Convert/ToRhino.cs [hunk 3]
```diff
@@ -272,10 +272,16 @@ public static RHG.PolyCurve ToRhino(this BHG.PolyCurve bPolyCurve)
...
+            //Appending disjoined curves to a single Rhino polycurves ensures it is joined and by doing so changes the geometry.
+            //Rhino Join is throwing access violation exceptions in some cases, leading to a full rhino crash, that can not be caught by a try-catch.
```
Comment (FraserGreenroyd) [inline Rhinoceros_Engine/Convert/ToRhino.cs:277]:
```suggestion
            //Rhino Join is throwing access violation exceptions in some cases, leading to a full Rhino crash, that cannot be caught by a try-catch.
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
I have not yet tested this Pull Request, only performed a code review.

My request for changes relate to the spelling on the comments and request for a date.

My other comments are for discussion, happy for them to be shot down as 'invalid' and resolved if appropriate.

File: Rhinoceros_Engine/Convert/ToRhino.cs (hunk 2 above)
Comment (IsakNaslundBh) [reply Rhinoceros_Engine/Convert/ToRhino.cs:275]: Date is ofc available here on github through the history, but can add it if you like

File: Rhinoceros_Engine/Convert/ToRhino.cs (hunk 1 above)
Comment (FraserGreenroyd) [reply Rhinoceros_Engine/Convert/ToRhino.cs:284]: This makes perfect sense to me, so happy not to make any further changes :smile:

File: Rhinoceros_Engine/Convert/ToRhino.cs (hunk 2 above)
Comment (FraserGreenroyd) [reply Rhinoceros_Engine/Convert/ToRhino.cs:275]: Have discussed this offline with @IsakNaslundBh and am happy without a date being included following discussion behind reasons.

File: Rhinoceros_Engine/Convert/ToRhino.cs [hunk 4]
```diff
@@ -272,10 +272,16 @@ public static RHG.PolyCurve ToRhino(this BHG.PolyCurve bPolyCurve)
...
+            //For this reason, the BHoM Join is used instead.
+            if (BH.Engine.Geometry.Compute.IJoin(bPolyCurve.Curves).Count > 1)
```
[the remark this answers is not in the document]
Comment (FraserGreenroyd) [reply Rhinoceros_Engine/Convert/ToRhino.cs:279]: Makes sense to me! MSTM - is that a new acronym we can use? 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Code looks fine, test script looked ok (didn't dig into it too deep). Happy to merge this to alpha for further testing by alpha users before we go to the next beta.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6129722289
