### PR TITLE
BHoM => Rhino BRep convert tolerance bug fixed

### LINKED ISSUE #170: Trimmed surface does not convert to BHoMGeometry correctly
#### Description:

Cannot explicitly cast Trimmed Surface to BHoMGeo. NurbsSurface is probably created correctly but cannot be exposed in Rhino.

#### Steps to reproduce:

See test file.

#### Expected behaviour:

Should convert to correct BHoM object.

#### Test file(s):

[On SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRhinoceros%5FToolkit%2FRhinoceros%5FToolkit%2DIssue170%2DTrimmed%20surface%20does%20not%20convert%20to%20BHoMGeometry%20correctly)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #170

### Test files

[On SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRhinoceros%5FToolkit%2FRhinoceros%5FToolkit%2DIssue170%2DTrimmed%20surface%20does%20not%20convert%20to%20BHoMGeometry%20correctly)

### Changelog

- BHoM => Rhino BRep convert tolerance bug fixed
- `Query.DocumentTolerance` method added

### Additional comments

Extra checks in `Query.DocumentTolerance` added to manage the case where the method is somehow called from outside of Rhino or there is no active document - better safe than sorry 😉

### CODE REVIEW

File: Rhinoceros_Engine/Query/DocumentTolerance.cs [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+        public static double DocumentTolerance()
+        {
+            RhinoDoc doc = Rhino.RhinoDoc.ActiveDoc;
+
+            if (doc != null)
+                return doc.ModelAbsoluteTolerance;
+            else
+            {
+                BH.Engine.Reflection.Compute.RecordError("Rhino document tolerance could not be retrieved because active document has not been found.");
+                return double.NaN;
```
Comment (epignatelli) [inline Rhinoceros_Engine/Query/DocumentTolerance.cs:42]: I am not sure returning something that is not a number is useful here.
This forces checks in downstream methods whether the tolerance is a valid signal or not.
`NaN` might be especially bad.

Is there a reason you are not returning the standard BHoM tolerance (maybe with a warning) when the doc tolerance fails?

Comment (pawelbaran) [reply Rhinoceros_Engine/Query/DocumentTolerance.cs:42]: Yeah, I was thinking about it too, but decided to record the error to inform the user that something went badly wrong instead of hiding the problem under a default value. However, I am 50/50 on that, can see the benefits of warning + returning the standard BHoM tolerance.

@al-fisher @LMarkowski how does that fit into the wider discussion about returning doubles on fail?

Comment (LMarkowski) [reply Rhinoceros_Engine/Query/DocumentTolerance.cs:42]: At this moment every not implemented case in the Geometry_Engine will return `double.NaN`. I'm not sure if it's to be expanded on every other error but to me that sounds reasonable.

Comment (IsakNaslundBh) [reply Rhinoceros_Engine/Query/DocumentTolerance.cs:42]: guess this is a question of returning something that for sure will make things fail and raise an error (current implementation) or return something that for many/most cases will work, but for some cases might not and raise a warning (@epignatelli suggestion).

Would probably err on the side of eduardos suggestion for this case. Personally think it is a slightly different context/situation compared to a method not being implemented in the Geometry_Engine, but good to get @al-fisher s oppinion on the matter as well.

Comment (epignatelli) [reply Rhinoceros_Engine/Query/DocumentTolerance.cs:42]: Yeah, I think the problem is that we are using our own logging mechanism to avoid throwing an exception, but we are returning `NaN`. The code will break somewhere else due to the `NaN`s. so that's not particularly useful.

Comment (al-fisher) [reply Rhinoceros_Engine/Query/DocumentTolerance.cs:42]: Yes - agreed - think this might be a sensible case to raise a warning and returning the standard BHoM tolerance.
With message explaining "no active document found - default BHoM tolerance returned."

Comment (pawelbaran) [reply Rhinoceros_Engine/Query/DocumentTolerance.cs]: Changes made, ready for review 👍

**Review by al-fisher — DISMISSED** [review]
LGTM

Tested on original files from @harrilewis in https://github.com/BHoM/Rhinoceros_Toolkit/issues/168
Now successfully coverting all faces of BRep - including original problem trimmed surface.

**Before**

image

**Now**

image


There are still issues with not returning a _CLOSED_ Boundary Representation. 
I think this is a similar tolerance issue. See workflow below that successfully enables closure of a BRep after conversion 
image
@pawelbaran @LMarkowski FYI

There is already an open issue regarding this - https://github.com/BHoM/Rhinoceros_Toolkit/issues/91
I will add more info and test files to this issue - and being out of scope for this PR - happy to approve this PR.

**Review by LMarkowski — COMMENTED** [review]
Code and test file generally look good. However I have two questions:
1. It seems that explode is failing to convert outer trims, but I'm not sure if I understand it correctly and than if it's in the scope of this PR.
image
2. Having new `DocumentTolerance` approach I wonder if it's worth applying to other convert methods which at the moment use BHoM tolerance. But that probably should wait until we have convert tests for all geometry types we talked on Friday's standup.

**Comment by IsakNaslundBh** [comment]
> It seems that explode is failing to convert outer trims, but I'm not sure if I understand it correctly and than if it's in the scope of this PR.

This we need to add an exception for the SurfaceTrims here:

image

To stop rhino toolkit from trying to convert the surface trims.

**Comment by al-fisher** [comment]
Oh - well done @LMarkowski, @IsakNaslundBh - would suggest worth adding that fix to this PR

**Comment by pawelbaran** [comment]
Done @al-fisher 👍

**Review by LMarkowski — APPROVED** [review]
👍 

image

**Comment by al-fisher** [comment]
Nice one! Thanks @pawelbaran
